import { SpriteSheetMetadata } from '@/types/export';
import { ProcessingSettings } from '@/types/processing';
import { VideoMetadata } from '@/types/video';
import { SPRITE_SHEET_METADATA_VERSION, GENERATOR_NAME } from '@/utils/constants';

/**
 * Generate metadata JSON for the sprite sheet
 * Includes all processing settings for reproducibility
 */
export function generateMetadata(
  frames: ImageData[],
  settings: ProcessingSettings,
  videoMetadata: VideoMetadata | null,
  spriteSheetDimensions: {
    cols: number;
    rows: number;
  }
): string {
  const metadata: SpriteSheetMetadata = {
    version: SPRITE_SHEET_METADATA_VERSION,
    generator: GENERATOR_NAME,
    timestamp: new Date().toISOString(),
    video: videoMetadata
      ? {
          originalFPS: videoMetadata.fps,
          originalDimensions: {
            width: videoMetadata.width,
            height: videoMetadata.height,
          },
        }
      : {
          originalFPS: 30,
          originalDimensions: {
            width: 0,
            height: 0,
          },
        },
    frames: {
      count: frames.length,
      size: frames[0]?.width || 0,
    },
    processing: {
      chromaKey: {
        color: settings.chromaKey.color,
        threshold: settings.chromaKey.threshold,
        feathering: settings.chromaKey.feathering,
      },
      sizing: {
        targetSize: settings.sizing.targetSize,
        paddingReduction: settings.sizing.paddingReduction,
        anchor: settings.sizing.anchor,
      },
      haloRemoval: {
        strength: settings.haloRemoval.strength,
      },
    },
    spriteSheet: {
      columns: spriteSheetDimensions.cols,
      rows: spriteSheetDimensions.rows,
    },
  };

  return JSON.stringify(metadata, null, 2);
}

/**
 * Generate a simple README for the export
 */
export function generateReadme(
  frameCount: number,
  frameSize: number,
  spriteSheetDimensions: {
    cols: number;
    rows: number;
    width: number;
    height: number;
  }
): string {
  return `# Sprite Sheet Export

Generated by Sprite Smithy
Generated: ${new Date().toLocaleString()}

## Contents

- sprite-sheet.png: Complete sprite sheet with all frames
- frames/: Individual frame files
- metadata.json: Processing settings and sprite sheet information

## Sprite Sheet Details

- Total Frames: ${frameCount}
- Frame Size: ${frameSize}×${frameSize}px
- Sprite Sheet Dimensions: ${spriteSheetDimensions.width}×${spriteSheetDimensions.height}px
- Grid Layout: ${spriteSheetDimensions.cols} columns × ${spriteSheetDimensions.rows} rows

## Usage

### In Game Engines

**Unity:**
1. Import sprite-sheet.png
2. Set Sprite Mode to Multiple
3. Use Sprite Editor to slice using:
   - Type: Grid By Cell Count
   - Columns: ${spriteSheetDimensions.cols}
   - Rows: ${spriteSheetDimensions.rows}

**Godot:**
1. Import sprite-sheet.png
2. Create AnimatedSprite or Sprite2D
3. Set Hframes to ${spriteSheetDimensions.cols}
4. Set Vframes to ${spriteSheetDimensions.rows}

**Phaser:**
\`\`\`javascript
this.load.spritesheet('sprite', 'sprite-sheet.png', {
  frameWidth: ${frameSize},
  frameHeight: ${frameSize}
});
\`\`\`

## Notes

- All frames are ${frameSize}×${frameSize}px with transparency
- Frames are arranged left-to-right, top-to-bottom
- Processing was deterministic - re-processing with same settings produces identical output

---

Made with Sprite Smithy - https://github.com/anthropics/sprite-smithy
`;
}
